call nasm main
call nasm dirxy
call nasm line
call nasm rwalls
call nasm lwalls
call nasm fcircle 
call nasm circle 
call nasm cursor 
call nasm caracter 
call nasm plot_xy
call nasm rect
call nasm frect
call nasm raquete
call nasm delay
call nasm intro
call nasm gameOver
call freelink main dirxy line rwalls lwalls fcircle circle cursor caracter plot_xy rect raquete delay frect intro gameOver
call del *.OBJ
call del *.LST